### ISSUE TITLE
Cost for parts and machining?

### ISSUE THREAD

**Issue by BrainofZedZed** [kavli-ntnu/MINI2P_toolbox#6]
Hello,

First, thank you for developing this amazing tool and going to great lengths to document it and enable others to build it. 
The Shopping and Machine list doesn't have the cost for each part listed in it. Could you estimate (rough approximation is fine) what the total part cost is to build one scope? And do those costs scale linearly or is just cheaper to buy some of the more expensive parts in multiples?

Thanks
Zach

**Comment by marinesrj** [comment]
Hello Zach,
Finally going through your question, I hope it is still helpful!
One scope costs approximately 6500EUR including one objective, 5 baseplates, 5 stitching adapters and one MEMS (Fast or Last). Indeed it is cheaper to buy some parts in bulk (e.g. stacked uTLens, machined scopebody parts), but others like objective does not make a difference. Please check excel spreadsheet under Protocols "Price MINI2P 2022" for more info.
