### ISSUE TITLE
Missing P3 Assembly Protocol

### ISSUE THREAD

**Issue by jrosh** [kavli-ntnu/MINI2P_toolbox#7]
Would it be possible to provide a print version of the mini2p assembly protocol in addition to the video?

**Comment by marinesrj** [comment]
P3 - Miniscope assembly protocol has been added under https://github.com/kavli-ntnu/MINI2P_toolbox/tree/main/Protocols
It should be available shortly. Thank you.

**Comment by marinesrj** [comment]
Link to MINI2P miniscope assembly protocol : https://github.com/kavli-ntnu/MINI2P_toolbox/blob/main/Protocols/P3%20-%20Miniscope%20assembly%20protocol%20.pdf
